### PR TITLE
Add DiscoveryService shared singleton

### PR DESCRIPTION
**Pull request by kurtz335**

### CODE REVIEW

**Comment by jaredfrees** [comment]
So I am going to add a .gitignore file in the repo, something I forgot to do on both of them to begin with. Can you remove the .idea folder from your commit and some other binary files. I will include the ones in the .gitignore and then you can just use that as reference

**Comment by jaredfrees** [comment]
Okay it is in there, I removed some of the files that don't need to be there. Can you remove the 'target' folder in your commit also if you can? I don't think there is a way to remove a folder in Github web

**Comment by kurtz335** [comment]
Just removed the stuff that you mentioned... let me know if there's anything else which needs to be deleted

**Comment by jaredfrees** [comment]
Cool I think that looks good thanks Nick

**Pull request merged**
