### PR TITLE
Message and PlantInfo Query endpoints added

### PR DESCRIPTION
**Pull request by kurtz335**
- added stubbed message endpoints (as a functional placeholder until we get the conversation platform to work)
- created PlantInfo object with basic fields and linked that with an endpoint to return a plant name for the keywords passed in with the request (the web project must pass an object with the same structure so the JSON parser can fill it in correctly)

### CODE REVIEW

**Review by jaredfrees — APPROVED** [review]

**Comment by jaredfrees** [comment]
One other thing, sorry to be picky about this, but can you not include the .class files next time? .class files are in the .gitignore file if you have the most recent version of the .gitignore

**Comment by kurtz335** [comment]
@jaredfrees yeah, my bad. I'll have to be more particular about it - I checked and I do have the most recent .gitignore, and *.class is in there... not sure why it's pushing them up. I'll make sure manually next time.

**Comment by kurtz335** [comment]
Actually wait - maybe some of these commits happened before the .gitignore was added so they stayed up and I never removed them from this branch before creating the PR. That's probably it. So I think those are from older commits. Either way, I'll double check again next time.

**Comment by jaredfrees** [comment]
You're good it's not a huge deal. Yeah that would make sense from older commits. I just wanted to make sure you saw the .gitignore. I should have remember to make it when I initially made the repos! It would have made it a lot easier

**Pull request merged**
